# This file was generated by GoReleaser. DO NOT EDIT.
cask "nirvana" do
  version "0.53.0"

  on_macos do
    on_intel do
      sha256 "e27295f65e3939b3a05fae6c5aa3f95d38274cb1dbdef24ec73cd8e6682f1560"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "4ca6e5c8585402dc0e8dae3fd4d1f8159d476f4ae47aa06375850ca750407d99"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "f1b34adedaa49fa44e94d3c76bf1a54039152fe152094b021e5c500b895e814c"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f191388dc8c180273f095c65794f8e9a9fa4cc2234b4d35f8c570d9ae93ef7fd"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nirvana"
  desc "Nirvana Labs CLI"
  homepage "https://nirvanalabs.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nirvana"
  manpage "man/man1/nirvana.1.gz"
  bash_completion "completions/nirvana.bash"
  fish_completion "completions/nirvana.fish"
  zsh_completion "completions/nirvana.zsh"

  # No zap stanza required

end
