# This file was generated by GoReleaser. DO NOT EDIT.
cask "nirvana" do
  version "0.54.4"

  on_macos do
    on_intel do
      sha256 "5d5e2a49dbbeb162bd773cba4a05798588c72ed773e30780c2f5a0880bf84096"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "7835cbcc09f722a10d31802aa9e83de8e5af904b0fced34c84203b945c910df2"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "a362b07c188172a524c52dcc530a4c9fd18b3f73e244befd773a6eb76bd535e1"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "efbe1f8126994be0d2650da127e0ad7a4ceab712dced4b2948295464c8b6a3c0"
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nirvana"
  desc "Nirvana Labs CLI"
  homepage "https://nirvanalabs.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nirvana"
  manpage "man/man1/nirvana.1.gz"
  bash_completion "completions/nirvana.bash"
  fish_completion "completions/nirvana.fish"
  zsh_completion "completions/nirvana.zsh"

  # No zap stanza required

end
