# This file was generated by GoReleaser. DO NOT EDIT.
cask "nirvana" do
  version "0.32.1"

  on_macos do
    on_intel do
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_macos_amd64.zip"
      sha256 "300bfc2b1d61695fd8eb3745df1d4a550f6f4ca1d0a54531a39f44145cd06195"
    end
    on_arm do
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_macos_arm64.zip"
      sha256 "977bff571d07bd96df84911a0474076f0e81b933c5efe305089f1ce3a60fe540"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_linux_amd64.tar.gz"
      sha256 "cdabe0bcc0c91794c2abd624ebfab3813843714b6a9a390cd2ebfe63b525f185"
    end
    on_arm do
      url "https://github.com/nirvana-labs/nirvana-cli/releases/download/v#{version}/nirvana_#{version}_linux_arm64.tar.gz"
      sha256 "d8783f4272a4c4ae4d18779ead12b784e967cde6a0caafc1ece82f5ac3f6744a"
    end
  end

  name "nirvana"
  desc "Nirvana Labs CLI"
  homepage "https://nirvanalabs.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nirvana"
  manpage "man/man1/nirvana.1.gz"
  bash_completion "completions/nirvana.bash"
  fish_completion "completions/nirvana.fish"
  zsh_completion "completions/nirvana.zsh"

  # No zap stanza required

end
